# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-21 15:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20160818_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(blank=True, max_length=256, unique=True),
        ),
    ]
