# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-23 15:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20160821_1522'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='id',
        ),
        migrations.AlterField(
            model_name='tag',
            name='title',
            field=models.CharField(blank=True, max_length=256, primary_key=True, serialize=False, unique=True),
        ),
    ]
